# Generated by Django 5.1.7 on 2025-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-time_create'], 'verbose_name': 'Знаменитость', 'verbose_name_plural': 'Знаменитости'},
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['-time_create'], name='star_star_time_cr_80a8dd_idx'),
        ),
    ]
