# Generated by Django 5.1.7 on 2025-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_alter_star_options_star_star_star_time_cr_80a8dd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
